name = "charli3-official/odv-multisig-charli3-oracle-onchain"
version = "0.0.0"
compiler = "v1.1.6"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'charli3-official/odv-multisig-charli3-oracle-onchain'"

[repository]
user = "charli3-official"
project = "odv-multisig-charli3-oracle-onchain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config.default]
disallow_less_than_four_nodes = true
core_settings_token_name = "C3CS"
reward_account_token_name = "C3RA"
reward_transport_token_name = "C3RT"
aggstate_token_name = "C3AS"

[config.testnet]
disallow_less_than_four_nodes = false
core_settings_token_name = "CoreSettings"
reward_account_token_name = "RewardAccount"
reward_transport_token_name = "RewardTransport"
aggstate_token_name = "AggregationState"
